version: "3"
services:
  # nginx:
  #   image: nginx:1.17
  #   volumes:
  #     - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
  #   ports:
  #     - 8000:80
  #   depends_on:
  #     - app
  app:
    container_name: etdp-qa
    image: index.docker.io/ohiageorge/odoo-etdp-qa:latest
    ports:
      - "8069:8069"
    volumes:
      - odoo-data:/var/lib/odoo
      - ./etc:/etc/odoo
      - ./addons:/mnt/extra-addons

  # watchtower:
  #   image: containrrr/watchtower
  #   container_name: watchtower
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  #   environment:
        # - WATCHTOWER_NOTIFICATIONS=email
        # - WATCHTOWER_NOTIFICATION_EMAIL_FROM=support@qisolutions.co.za
        # - WATCHTOWER_NOTIFICATION_EMAIL_TO=ohiageorge@gmail.com
        # - WATCHTOWER_NOTIFICATION_EMAIL_SERVER=mail.smtp2go.com
        # - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_USER=QISolutions
        # - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PASSWORD=PPIPsxEizqZnUkk1
        # - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PORT=25
        # - WATCHTOWER_NOTIFICATION_EMAIL_DELAY=2
        # - WATCHTOWER_CLEANUP=true
        # -WATCHTOWER_MONITOR_ONLY=true
    # command: --interval 30 etdp-qa
    # restart: unless-stopped
  #   networks:
  #     - watchtower
  # networks:
  #   watchtower:
  #     external: false
volumes:
  odoo-data:

